export const ACTION_TYPES = {
    CHANGE_INPUT: "CHANGE_INPUT",
    ADD_SKILL: "ADD_SKILL",
    ADD_EXPERIENCE: "ADD_EXPERIENCE",
    REMOVE_SKILL: "REMOVE_SKILL",
    REMOVE_EXPERIENCE: "REMOVE_EXPERIENCE",
}